### ISSUE TITLE
极空间更新后所有都显示没有更新，实际有更新

### ISSUE THREAD

**Issue by denglinfu** [onlyLTY/dockerCopilotZspace#4]
版本是最新的 2.04
已经设置了代理，在 portainer 中可以正常拉取镜像
日志有对应错误提示
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/b573d4ce-94c1-4422-8a3e-48a8c48390b8">
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/e97bdb48-6344-4160-9faf-d8cb32eb57bd">

补充一下，虽然没有提示更新，但是如果点击更新也会将制定的 docker 更新到最新版

**Comment by denglinfu** [comment]
> 版本是最新的 2.04 已经设置了代理，在 portainer 中可以正常拉取镜像

日志有对应提示
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/e229b513-282f-4887-b03e-6e8ac05c0ec3">

**Comment by fluffymm** [comment]
同样遇到了这个问题，所有镜像显示最新，实际上有更新了

**Comment by onlyLTY** [comment]
最新版本已做优化处理。请帮忙看一下正常了没

**Comment by Rabbit-Spec** [comment]
> 最新版本已做优化处理。请帮忙看一下正常了没

最新2.0.7部分容器还是检测不到更新，比如ha有10.2更新了，但是我10.1版本检测还是最新版。

**Comment by Rabbit-Spec** [comment]
> 最新版本已做优化处理。请帮忙看一下正常了没

�2024-10-12T14:33:10.783942858Z 2024-10-12T22:33:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.7Mi, TotalAlloc=6918.8Mi, Sys=13.8Mi, NumGC=3302	caller=stat/usage.go:61
�2024-10-12T14:33:13.096639319Z 2024-10-12T22:33:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
}2024-10-12T14:33:32.483244357Z 2024-10-12T22:33:32.482+08:00	 info 	image name openspeedtest/latest	caller=module/auth.go:25
�2024-10-12T14:33:32.483255607Z 2024-10-12T22:33:32.482+08:00	 error 	获取digest失败Head "https://index.docker.io/v2/networkstatic/iperf3/manifests/latest": dial tcp [2a03:2880:f129:83:face:b00c:0:25de]:443: i/o timeout	caller=module/checkupdate.go:54
�2024-10-12T14:33:33.520340514Z 2024-10-12T22:33:33.520+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:33:37.485405306Z 2024-10-12T22:33:37.484+08:00	 error 	Failed to connect to https://index.docker.io: Head "https://index.docker.io": context deadline exceeded (Client.Timeout exceeded while awaiting headers)	caller=module/auth.go:183
�2024-10-12T14:33:37.489780807Z 2024-10-12T22:33:37.489+08:00	 error 	Failed to connect to https://qazxsw.msaber.fun: Head "https://qazxsw.msaber.fun": dial tcp: lookup qazxsw.msaber.fun on 192.168.50.1:53: no such host	caller=module/auth.go:183
2024-10-12T14:34:07.491222903Z 2024-10-12T22:34:07.490+08:00	 error 	获取token失败或者无需获取token，继续尝试检查Get "https://index.docker.io/v2/": dial tcp [2a03:2880:f129:83:face:b00c:0:25de]:443: i/o timeout	caller=module/checkupdate.go:45
�2024-10-12T14:34:10.784803602Z 2024-10-12T22:34:10.784+08:00	 stat 	CPU: 1m, MEMORY: Alloc=3.5Mi, TotalAlloc=6922.5Mi, Sys=13.8Mi, NumGC=3304	caller=stat/usage.go:61
�2024-10-12T14:34:12.491855399Z 2024-10-12T22:34:12.491+08:00	 error 	Failed to connect to https://index.docker.io: Head "https://index.docker.io": context deadline exceeded (Client.Timeout exceeded while awaiting headers)	caller=module/auth.go:183
2024-10-12T14:34:12.634602545Z 2024-10-12T22:34:12.634+08:00	 error 	Failed to connect to https://qazxsw.msaber.fun: Head "https://qazxsw.msaber.fun": tls: failed to verify certificate: x509: certificate is valid for danmuji.neuedu.work, not qazxsw.msaber.fun	caller=module/auth.go:183
�2024-10-12T14:34:13.096733297Z 2024-10-12T22:34:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 3, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:34:33.521136169Z 2024-10-12T22:34:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:34:42.636007730Z 2024-10-12T22:34:42.635+08:00	 error 	获取digest失败Head "https://index.docker.io/v2/openspeedtest/latest/manifests/latest": dial tcp [2a03:2880:f129:83:face:b00c:0:25de]:443: i/o timeout	caller=module/checkupdate.go:54
�2024-10-12T14:35:10.783743276Z 2024-10-12T22:35:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=3.4Mi, TotalAlloc=6926.3Mi, Sys=13.8Mi, NumGC=3306	caller=stat/usage.go:61
�2024-10-12T14:35:13.096526428Z 2024-10-12T22:35:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:35:33.519824407Z 2024-10-12T22:35:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:36:10.783419888Z 2024-10-12T22:36:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=3.3Mi, TotalAlloc=6929.9Mi, Sys=13.8Mi, NumGC=3308	caller=stat/usage.go:61
�2024-10-12T14:36:13.096689321Z 2024-10-12T22:36:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:36:33.520309603Z 2024-10-12T22:36:33.520+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:37:10.783679295Z 2024-10-12T22:37:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.3Mi, TotalAlloc=6933.6Mi, Sys=13.8Mi, NumGC=3310	caller=stat/usage.go:61
�2024-10-12T14:37:13.096772865Z 2024-10-12T22:37:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:37:33.520176267Z 2024-10-12T22:37:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:38:10.784394832Z 2024-10-12T22:38:10.784+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.3Mi, TotalAlloc=6937.2Mi, Sys=13.8Mi, NumGC=3312	caller=stat/usage.go:61
�2024-10-12T14:38:13.096091314Z 2024-10-12T22:38:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:38:33.519615083Z 2024-10-12T22:38:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:39:10.784226887Z 2024-10-12T22:39:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=2.9Mi, TotalAlloc=6940.8Mi, Sys=13.8Mi, NumGC=3314	caller=stat/usage.go:61
�2024-10-12T14:39:13.095945682Z 2024-10-12T22:39:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:39:33.520478912Z 2024-10-12T22:39:33.520+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:40:10.784338523Z 2024-10-12T22:40:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=2.5Mi, TotalAlloc=6944.5Mi, Sys=13.8Mi, NumGC=3316	caller=stat/usage.go:61
�2024-10-12T14:40:13.096625586Z 2024-10-12T22:40:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:40:33.520348505Z 2024-10-12T22:40:33.520+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:41:10.783418913Z 2024-10-12T22:41:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=2.1Mi, TotalAlloc=6948.1Mi, Sys=13.8Mi, NumGC=3318	caller=stat/usage.go:61
�2024-10-12T14:41:13.096212628Z 2024-10-12T22:41:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:41:33.520229936Z 2024-10-12T22:41:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:42:10.783800465Z 2024-10-12T22:42:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.7Mi, TotalAlloc=6951.7Mi, Sys=13.8Mi, NumGC=3319	caller=stat/usage.go:61
�2024-10-12T14:42:13.096323628Z 2024-10-12T22:42:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:42:33.519468953Z 2024-10-12T22:42:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:43:10.783568975Z 2024-10-12T22:43:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.3Mi, TotalAlloc=6955.4Mi, Sys=13.8Mi, NumGC=3321	caller=stat/usage.go:61
�2024-10-12T14:43:13.096013464Z 2024-10-12T22:43:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:43:33.520349519Z 2024-10-12T22:43:33.520+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:44:10.784080831Z 2024-10-12T22:44:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=2.8Mi, TotalAlloc=6959.0Mi, Sys=13.8Mi, NumGC=3323	caller=stat/usage.go:61
�2024-10-12T14:44:13.096534480Z 2024-10-12T22:44:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:44:33.519439696Z 2024-10-12T22:44:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:45:10.783995841Z 2024-10-12T22:45:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=2.3Mi, TotalAlloc=6962.6Mi, Sys=13.8Mi, NumGC=3325	caller=stat/usage.go:61
�2024-10-12T14:45:13.096528446Z 2024-10-12T22:45:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:45:33.520415130Z 2024-10-12T22:45:33.520+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:46:10.783817564Z 2024-10-12T22:46:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=1.8Mi, TotalAlloc=6966.3Mi, Sys=13.8Mi, NumGC=3327	caller=stat/usage.go:61
�2024-10-12T14:46:13.096663004Z 2024-10-12T22:46:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:46:33.519726205Z 2024-10-12T22:46:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:47:10.784295192Z 2024-10-12T22:47:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=3.4Mi, TotalAlloc=6969.9Mi, Sys=13.8Mi, NumGC=3328	caller=stat/usage.go:61
�2024-10-12T14:47:13.095729631Z 2024-10-12T22:47:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:47:33.520313136Z 2024-10-12T22:47:33.520+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:48:10.783581399Z 2024-10-12T22:48:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=3.0Mi, TotalAlloc=6973.5Mi, Sys=13.8Mi, NumGC=3330	caller=stat/usage.go:61
�2024-10-12T14:48:13.095975217Z 2024-10-12T22:48:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:48:33.519486708Z 2024-10-12T22:48:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:49:10.783873004Z 2024-10-12T22:49:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=2.5Mi, TotalAlloc=6977.2Mi, Sys=13.8Mi, NumGC=3332	caller=stat/usage.go:61
�2024-10-12T14:49:13.096450702Z 2024-10-12T22:49:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:49:33.519875052Z 2024-10-12T22:49:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:50:10.783952748Z 2024-10-12T22:50:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=2.0Mi, TotalAlloc=6980.8Mi, Sys=13.8Mi, NumGC=3334	caller=stat/usage.go:61
�2024-10-12T14:50:13.096158318Z 2024-10-12T22:50:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:50:33.519752210Z 2024-10-12T22:50:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:51:10.784091807Z 2024-10-12T22:51:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.6Mi, TotalAlloc=6984.4Mi, Sys=13.8Mi, NumGC=3335	caller=stat/usage.go:61
�2024-10-12T14:51:13.095876631Z 2024-10-12T22:51:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:51:33.519461200Z 2024-10-12T22:51:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:52:10.783717945Z 2024-10-12T22:52:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=3.1Mi, TotalAlloc=6988.1Mi, Sys=13.8Mi, NumGC=3337	caller=stat/usage.go:61
�2024-10-12T14:52:13.095886303Z 2024-10-12T22:52:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:52:33.519686447Z 2024-10-12T22:52:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:53:10.784134290Z 2024-10-12T22:53:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=2.7Mi, TotalAlloc=6991.7Mi, Sys=13.8Mi, NumGC=3339	caller=stat/usage.go:61
�2024-10-12T14:53:13.096561070Z 2024-10-12T22:53:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:53:33.520101248Z 2024-10-12T22:53:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:54:10.783876666Z 2024-10-12T22:54:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=2.2Mi, TotalAlloc=6995.4Mi, Sys=13.8Mi, NumGC=3341	caller=stat/usage.go:61
�2024-10-12T14:54:13.096312522Z 2024-10-12T22:54:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:54:33.519753776Z 2024-10-12T22:54:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:55:10.783636498Z 2024-10-12T22:55:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.8Mi, TotalAlloc=6999.0Mi, Sys=13.8Mi, NumGC=3342	caller=stat/usage.go:61
�2024-10-12T14:55:13.096421694Z 2024-10-12T22:55:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:55:33.519732777Z 2024-10-12T22:55:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:56:10.783397301Z 2024-10-12T22:56:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.3Mi, TotalAlloc=7002.6Mi, Sys=13.8Mi, NumGC=3344	caller=stat/usage.go:61
�2024-10-12T14:56:13.096426564Z 2024-10-12T22:56:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:56:33.519787799Z 2024-10-12T22:56:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:57:10.784309559Z 2024-10-12T22:57:10.784+08:00	 stat 	CPU: 1m, MEMORY: Alloc=2.8Mi, TotalAlloc=7006.3Mi, Sys=13.8Mi, NumGC=3346	caller=stat/usage.go:61
�2024-10-12T14:57:13.096166596Z 2024-10-12T22:57:13.095+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:57:33.519566156Z 2024-10-12T22:57:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:58:10.784065357Z 2024-10-12T22:58:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=2.3Mi, TotalAlloc=7009.9Mi, Sys=13.8Mi, NumGC=3348	caller=stat/usage.go:61
�2024-10-12T14:58:13.096432336Z 2024-10-12T22:58:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:58:33.519457278Z 2024-10-12T22:58:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T14:59:10.784057611Z 2024-10-12T22:59:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=1.8Mi, TotalAlloc=7013.5Mi, Sys=13.8Mi, NumGC=3350	caller=stat/usage.go:61
�2024-10-12T14:59:13.096548350Z 2024-10-12T22:59:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T14:59:33.519710197Z 2024-10-12T22:59:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T15:00:10.784158582Z 2024-10-12T23:00:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=3.5Mi, TotalAlloc=7017.2Mi, Sys=13.8Mi, NumGC=3351	caller=stat/usage.go:61
�2024-10-12T15:00:13.096465704Z 2024-10-12T23:00:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T15:00:33.520018284Z 2024-10-12T23:00:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T15:01:10.784158638Z 2024-10-12T23:01:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=3.0Mi, TotalAlloc=7020.8Mi, Sys=13.8Mi, NumGC=3353	caller=stat/usage.go:61
�2024-10-12T15:01:13.096559340Z 2024-10-12T23:01:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T15:01:33.519497857Z 2024-10-12T23:01:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T15:02:10.783399837Z 2024-10-12T23:02:10.783+08:00	 stat 	CPU: 0m, MEMORY: Alloc=2.5Mi, TotalAlloc=7024.4Mi, Sys=13.8Mi, NumGC=3355	caller=stat/usage.go:61
�2024-10-12T15:02:13.096651626Z 2024-10-12T23:02:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 0, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
�2024-10-12T15:02:33.519462941Z 2024-10-12T23:02:33.519+08:00	 stat 	(dockerCopilot) - qps: 0.0/s, drops: 0, avg time: 0.0ms, med: 0.0ms, 90th: 0.0ms, 99th: 0.0ms, 99.9th: 0.0ms	caller=stat/metrics.go:210
�2024-10-12T15:03:10.783810039Z 2024-10-12T23:03:10.783+08:00	 stat 	CPU: 1m, MEMORY: Alloc=2.0Mi, TotalAlloc=7028.1Mi, Sys=13.8Mi, NumGC=3357	caller=stat/usage.go:61
�2024-10-12T15:03:13.096414789Z 2024-10-12T23:03:13.096+08:00	 stat 	(api) shedding_stat [1m], cpu: 1, total: 0, pass: 0, drop: 0	caller=load/sheddingstat.go:61
