### ISSUE TITLE
开启了极空间的docker代理，dockercopilot无法检测到更新。给copilot设置了http_proxy和https_proxy还是无法检测更新。

### ISSUE THREAD

**Issue by yyzxq1** [onlyLTY/dockerCopilotZspace#8]
在极空间docker容器运行了clash容器， 设置docker代理指向clash的7890端口，copilot无法检测到更新。给copilot加上环境变量http_proxy和https_proxy还是无法检测到新版本。全部显示最新版本。
点击更新后原来的文件名变为一串hash sha256的乱码。
用极空间的虚拟机新建了个win10系统设置代理指向极空间的7890端口可以上google，排除clash和订阅问题。
设置极空间网关指向旁路网关（有openclash）后检测到更新，可以正常更新。
copilot版本2.07
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/08ab86ee-0a2b-4d9d-a87f-83c68ae0c378">

**Comment by yzxq1** [comment]
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/42a4c624-9aed-4405-97f6-3fe462d2ebeb">
更新了2.08 ，只开启docker ui的代理还是无法联通。
再增加对docker设置了https_proxy和http_proxy仍然失败
<img width="235" alt="image" src="https://github.com/user-attachments/assets/13caaa19-6384-46eb-810d-57618afcdfeb">
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/8a529f62-d39a-4283-9873-033bff46c776">

**Comment by yyzxq1** [comment]
<img width="529" alt="image" src="https://github.com/user-attachments/assets/d1aea599-56b1-4b59-8ef3-de11f45276c3">

**Comment by yzxq1** [comment]
<img width="497" alt="image" src="https://github.com/user-attachments/assets/4ee9faf2-3598-4394-9b5f-602c05e29260">

**Comment by onlyLTY** [comment]
copilot更新自身是在检测到更新的时候在左下角会出现一个更新按钮。为了防止误解，屏蔽了检测copilot自身更新

**Comment by yzxq1** [comment]
没有解决啊，还是检测不到更新，为什么issue被关闭了
![image](https://github.com/user-attachments/assets/6ba7a258-8fad-4064-a052-b039a3cd7699)
![image](https://github.com/user-attachments/assets/264d63f6-2e95-4f0d-b4cf-bee1379e1112)

**Comment by onlyLTY** [comment]
> 没有解决啊，还是检测不到更新，为什么issue被关闭了 ![image](https://private-user-images.githubusercontent.com/106797409/385167185-6ba7a258-8fad-4064-a052-b039a3cd7699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTM3NDcsIm5iZiI6MTczMTM5MzQ0NywicGF0aCI6Ii8xMDY3OTc0MDkvMzg1MTY3MTg1LTZiYTdhMjU4LThmYWQtNDA2NC1hMDUyLWIwMzlhM2NkNzY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNjM3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDkxNTJhYWVjODRlNTQ3YmU0NTcyNTZhMWYwZTYwM2NiNDk0MDEzMWMzZmRiNjQzY2E0MDIxODlkMmYyNDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZfEIUDe3ByzRyEC37NjDx6Zsvx6Ggh_eekezV-3f8m0) ![image](https://private-user-images.githubusercontent.com/106797409/385167297-264d63f6-2e95-4f0d-b4cf-bee1379e1112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTM3NDcsIm5iZiI6MTczMTM5MzQ0NywicGF0aCI6Ii8xMDY3OTc0MDkvMzg1MTY3Mjk3LTI2NGQ2M2Y2LTJlOTUtNGYwZC1iNGNmLWJlZTEzNzllMTExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNjM3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2ViYWI3MjE4NThkY2YzNTRjYTk4MDE3NzcwMmRhZjc2MDUzZTJmYTdhZGU0YjcyNjUyNjNmZWYzNzYxZDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jwq0USPyIfRvCH-G5YFNwF3xWwUqndtlj-qJcjbKnZw)

麻烦重启下dc。等待一分钟。然后提取下日志
